<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MAX.Messenger.API</RootNamespace>
    <Nullable>enable</Nullable>
	  
    <PackageId>MAX.Messenger.API</PackageId>
    <Version>0.1.0</Version>
    <Authors>Gennady Goncharov</Authors>
    <Company>BizChatBots</Company>
    <Description>Unofficial .NET client for MAX Messenger API</Description>

	<PackageTags>max;messenger;bot;api</PackageTags>
	<PackageProjectUrl>https://github.com/genixg/MAX.Messenger.API</PackageProjectUrl>
	<PackageIcon>max-icon.png</PackageIcon>
	<RepositoryUrl>https://github.com/genixg/MAX.Messenger.API</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	  
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<ImplicitUsings>enable</ImplicitUsings>
	  
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
	<None Include="max-icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
